version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .envs/.env.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
