# Use the official Python image
FROM python:3.10

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev musl-dev

# Copy requirements and install dependencies
COPY requirements /app/requirements
RUN pip install --no-cache-dir -r requirements/local.txt

# Copy the entire project
COPY . .

EXPOSE 8000

# Run the development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
