version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn one_click_convert.wsgi:application --bind 0.0.0.0:8000 --workers 4"
